#!/bin/bash -x
# define aliases for working with regional-base source is inputs for webpack, parcel-bundler

alias put='/bin/cp -f ./main.js ../../osm-source/regional-base/main.js;/bin/cp -f ./index.html ../../osm-source/regional-base/index.html;/bin/cp -f ./build/* ../../osm-source/regional-base/build/'
alias get='/bin/cp -f ../../osm-source/regional-base/index.html ./index.html;/bin/cp -f ../../osm-source/regional-base/main.js ./main.js;/bin/cp -f ../../osm-source/regional-base/ol5-layerswitcher.js ./ol5-layerswitcher.js'
alias dif='vimdiff ../../osm-source/regional-base/main.js ./main.js'
