#!/bin/bash -x
# define aliases for working with test source is inputs for webpack, parcel-bundler

alias put='/bin/cp -f ./main.js ../../osm-vector/test/test.js;/bin/cp -f ./index.html ../../osm-vector/test/test-index.html'
alias get='/bin/cp -f ../../osm-vector/test/test-index.html ./index.html;/bin/cp -f ../../osm-vector/test/test.js ./main.js'
alias dif='vimdiff ../../osm-vector/test/test.js ./main.js'
alias pub='scp ./build/main.js ghunt@unleashkids.org:/home/ghunt'
