#!/bin/bash
# download new copies of satellite.mbtiles and bboxes.json

source_url=https://archive.org/download
SATELLITE=satellite_z0-z9_v3.mbtiles
dest_dir=/library/www/osm-vector-maps/tiles

wget -c $source_url/$SATELLITE/$SATELLITE $PROGRES -P $dest_dir


osm_repo_url: https://raw.githubusercontent.com/iiab/maps
dest_dir=/library/www/osm-vector-maps/assets/

wget -c $osm_repo_url/osm-source/viewer/assets/bboxes.geojson $PROGRES -P $dest_dir
