#!/bin/bash -x
# define aliases for working with splash source is inputs for webpack, parcel-bundler

alias put='/bin/cp .f ./src/main.js ../osm-vector/splash/splash.js;cp -f ./src/index.html ../osm-vector/splash/splash-index.html'
alias get='/bin/cp -f ../osm-vector/splash/splash-index.html ./src/index.html;/bin/cp -f ../osm-vector/splash/splash.js ./src/main.js'
alias dif='vimdiff ../osm-vector/splash/splash.js ./src/main.js'
