#!/bin/bash -xe
# compile the javascript for this page and copy for execution in html server tree"

cp -fp ./webpack.config.js ../webpack/
cp -fp ./main.js ../webpack
cp -fp ./index.html ../webpack
cp -fp ./map.css ../webpack
cp -fp ./installer_functions.js ../webpack
cp -fp ./style-osm.json  ../webpack

cd ../webpack

npm run build
:
cd /opt/iiab/maps/osm-source/pages/installer
cp ./build/* /library/www/osm-vector-maps/installer
cp ./installer_functions.js /library/www/osm-vector-maps/installer/
cp ./map.css /library/www/osm-vector-maps/installer/
