#!/bin/bash

if [ -z "$1" ] || [ -z "$2" ]; then
  echo "Usage: ./$0 [find string] [replace string]"
  exit 1
fi
 
FIND=$1
REPLACE=$2

find . -type f -exec sed -i "s|${FIND}|${REPLACE}|g" {} +
exit 0
