#!/bin/bash -x
# define aliases for working with console source as inputs for webpack, parcel-bundler

alias put='/bin/cp -f ./main.js ../../osm-vector/console/main.js;/bin/cp -f ./index.html ../../osm-vector/console/index.html'
alias get='/bin/cp -f ../../osm-vector/console/index.html ./index.html;/bin/cp -f ../../osm-vector/console/main.js ./main.js'
alias dif='vimdiff ../../osm-vector/console/main.js ./main.js'
